# Generated by Django 4.2.4 on 2023-11-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default=1994),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password1',
            field=models.CharField(default='mama@gmail.com'),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='mustafo'),
            preserve_default=False,
        ),
    ]
