# Generated by Django 4.2.4 on 2024-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_rename_createdat_todos_date_rename_todo_todos_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField()),
                ('isAdmin', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
